CarDealerShip/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView # new


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('search.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # new
]

accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

search/urls.py
from django.urls import path

from . import views


app_name = 'search'
urlpatterns = [
   # path('', views.show_genres, name='index'),
    path('', views.IndexView.as_view(), name='index' ),
    path('make/<int:pk>', views.ResultsView.as_view(), name='results'),
    path('make/<int:pk>/model/<int:pk>', views.ResultsView.as_view(), name='results'),
#    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

search/models.py
import datetime
import mptt
import time
from django.db import models
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from django import template
register = template.Library()


from mptt.models import TreeForeignKey, MPTTModel
from django.contrib.auth.models import Group

# Create your models here.
YEARMONTH_INPUT_FORMATS = (
    '%Y-%m', '%m/%Y', '%m/%y', # '2006-10', '10/2006', '10/06'
)


class YearMonthField(models.CharField):
    default_error_messages = {
        'invalid': _('Enter a valid year and month.'),
    }

    def __init__(self, input_formats=None, *args, **kwargs):
        super(YearMonthField, self).__init__(*args, **kwargs)
        self.input_formats = input_formats

    def clean(self, value):
        if value in self.validators.EMPTY_VALUES:
            return None
        if isinstance(value, datetime.datetime):
            return format(value, '%Y-%m')
        if isinstance(value, datetime.date):
            return format(value, '%Y-%m')
        for fmt in self.input_formats or YEARMONTH_INPUT_FORMATS:
            try:
                date = datetime.date(*time.strptime(value, fmt)[:3])
                return format(date, '%Y-%m')
            except ValueError:
                continue
        raise ValidationError(self.error_messages['invalid'])


class Make(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return str(self.name)


class Model(models.Model):
    name = models.CharField(max_length=40)
    make =  models.ForeignKey(Make, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)


class SubModel(models.Model):
    name = models.CharField(max_length=50)
    model = models.ForeignKey(Model, on_delete=models.CASCADE)
    model_year = YearMonthField(max_length=20)

    def __str__(self):
        return str(self.name)


# TreeForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True).contribute_to_class(Group, 'Make')
# mptt.register(Group, order_insertion_by=['name'])


class Car(models.Model):
    LPG = 'LPG'
    GASOLINE = 'GAS'
    DIESEL = 'DIESEL'
    HYBRID = 'HYBRID'
    ELECTRIC = 'ELEC'
    BIFUEL = 'BI'
    FUEL_CHOICES = [
        (LPG, 'lpg'),
        (GASOLINE, 'gasoline'),
        (DIESEL, 'diesel'),
        (HYBRID, 'HYBRID'),
        (ELECTRIC, 'electric'),
        (BIFUEL, 'bi_fuel'),
    ]

    AUTO = 'AUTO'
    MANUAL = 'MAN'
    GEAR_CHOICES = [
        (AUTO, 'auto'),
        (MANUAL, 'manual'),
    ]

    PENDING = 'pend'
    INAUCTION = 'auction'



    DONEAUCTION = 'done'

    STATUS_CHOICES = [
        (PENDING, 'pending'),
        (INAUCTION, 'in_auction'),
        (DONEAUCTION, 'done_auction')

    ]
    registered_day = models.DateField('Registered Date')
    sub_model = models.ForeignKey(SubModel, on_delete=models.CASCADE, null=True)
    color = models.CharField(max_length=20)
    fuel = models.CharField(
        max_length=6,
        choices=FUEL_CHOICES,
        default=GASOLINE,
    )
    gear = models.CharField(
        max_length=4,
        choices=GEAR_CHOICES,
        default=AUTO,
    )
    kms = models.IntegerField(null=True)
    region = models.CharField(max_length=30)
    status = models.CharField(
        max_length=7,
        choices=STATUS_CHOICES,
        default=PENDING,
    )
    photo = models.ImageField(null=True)

    def __str__(self):
        return str(self.sub_model)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

search/views.py
import json
from .models import Car, Make, Model, SubModel
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404, render

from django.http import Http404, HttpResponse

#from infinite_scroll_pagination import paginator
#from infinite_scroll_pagination import serializers
#
#
# def pagination_ajax(request):
#     if not request.is_ajax():
#         return Http404()
#
#     try:
#         value, pk = serializers.page_key(request.GET.get('p', ''))
#     except serializers.InvalidPage:
#         return Http404()
#
#     try:
#         page = paginator.paginate(
#             query_set=Car.objects.all(),
#             lookup_field='registered_day',
#             value=value,
#             pk=pk,
#             per_page=20,
#             move_to=paginator.NEXT_PAGE)
#     except paginator.EmptyPage:
#         data = {'error': "this page is empty"}
#     else:
#         data = {
#             'articles': [{'title': article.title} for article in page],
#             'has_next': page.has_next(),
#             'has_prev': page.has_previous(),
#             'next_objects_left': page.next_objects_left(limit=100),
#             'prev_objects_left': page.prev_objects_left(limit=100),
#             'next_pages_left': page.next_pages_left(limit=100),
#             'prev_pages_left': page.prev_pages_left(limit=100),
#             'next_page': serializers.to_page_key(**page.next_page()),
#             'prev_page': serializers.to_page_key(**page.prev_page())}
#
#     return HttpResponse(json.dumps(data), content_type="application/json")
#
# def show_genres(request):
#     return render(request, "search/index.html", {'genres': Make.objects.all()})


class IndexView(generic.ListView):
    model = 'Make'
    template_name = 'search/index.html'
    context_object_name = 'make'
    #
    # def get_queryset(self):
    #     return Car.objects.order_by('-pub_date')[:5]
    #
    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['model'] = Model.objects.all()
        return context

    def get_queryset(self):
        return Model.objects.all()
    #
    #     return render(request, '/category_list.html', {'categories': categories})

class SearchView(generic.ListView):
    template_name = 'search/search_list.html'
    context_object_name = 'latest_question_list'

#     def get_queryset(self):
#         return Question.objects.order_by('-pub_date')[:5]
#
class DetailView(generic.DetailView):
    model = Model
    template_name = 'search/detail.html'
#

class ResultsView(generic.ListView):
    model = Model
    template_name = 'search/results.html'

search/templates/search/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Car DealerShip{% endblock %}</title>

</head>

<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

search/templates/search/detail.html
{% extends 'index.html' %}

search/templates/search/index.html
{% extends 'base.html' %}

{% block title %}Make{% endblock %}

{% block content %}
{% if user.is_authenticated %}


<style>
ul, #myUL {
  list-style-type: none;
}

#myUL {
  margin: 0;
  padding: 0;
}

.caret {
  cursor: pointer;
  -webkit-user-select: none; /* Safari 3.1+ */
  -moz-user-select: none; /* Firefox 2+ */
  -ms-user-select: none; /* IE 10+ */
  user-select: none;
}

.caret::before {
  content: "\25B6";
  color: black;
  display: inline-block;
  margin-right: 6px;
}

.caret-down::before {
  -ms-transform: rotate(90deg); /* IE 9 */
  -webkit-transform: rotate(90deg); /* Safari */'
  transform: rotate(90deg);
}

.nested {
  display: none;
}

.active {
  display: block;
}
</style>
    <h2>Tree View</h2>
    <p>A tree view represents a hierarchical view of information, where each item can have a number of subitems.</p>
    <p>Click on the arrow(s) to open or close the tree branches.</p>

    {% for single_make in make %}
    <ul id="myUL">
        <a href ="{% url 'search:results' pk=single_make.id%}"><span class="caret">{{single_make}}</span></a>
        <ul class="nested">

          <li><span class="caret"></span>
            <ul class="nested">
              <li>Black Tea</li>
              <li>White Tea</li>
              <li><span class="caret">Green Tea</span>
                <ul class="nested">
                  <li>Sencha</li>
                  <li>Gyokuro</li>
                  <li>Matcha</li>
                  <li>Pi Lo Chun</li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </ah>
    </ul>
    {% endfor %}
{% else %}
    You need to Login Frist!
    <a href="{% url 'login' %}">login</a>
{% endif %}

<script>
var toggler = document.getElementsByClassName("caret");
var i;

for (i = 0; i < toggler.length; i++) {
  toggler[i].addEventListener("click", function() {
    this.parentElement.querySelector(".nested").classList.toggle("active");
    this.classList.toggle("caret-down");
  });
}
</script>
{% endblock %}

search/templates/search/results.html
{% extends 'index.html' %}

{% block title %}Home{% endblock %}
{% block content %}
 <ul class="nested">

          <li><span class="caret"></span>
            <ul class="nested">
              <li>Black Tea</li>
              <li>White Tea</li>
              <li><span class="caret">Green Tea</span>
                <ul class="nested">
                  <li>Sencha</li>
                  <li>Gyokuro</li>
                  <li>Matcha</li>
                  <li>Pi Lo Chun</li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>

<script>
var toggler = document.getElementsByClassName("caret");
var i;

for (i = 0; i < toggler.length; i++) {
  toggler[i].addEventListener("click", function() {
    this.parentElement.querySelector(".nested").classList.toggle("active");
    this.classList.toggle("caret-down");
  });
}
</script>

    {% endblock %}

templates/base.html
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Car DealerShip{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <a href="{% url 'logout' %}">logout</a>
  <a href="{% url 'search:index' %}">search cars</a>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
  <br>
  <a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}